import Head from 'next/head';
import { useState, useEffect } from 'react';
import '@/styles/globals.css';
import Sidebar from '@/components/Sidebar';

export default function App({ Component, pageProps }) {
  const [closeSidebar, setCloseSidebar] = useState(false);
  const handleSidebar = () => {
    setCloseSidebar(prev => !prev);
  };

  const handleResize = () => {
    if (window.innerWidth <= 540) {
      setCloseSidebar(true);
    } else {
      setCloseSidebar(false);
    }
  };
  useEffect(() => {
    window.addEventListener('resize', handleResize);

    handleResize();

    return () => window.removeEventListener('resize', handleResize);
  }, []);

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/binance.png" />
      </Head>
      <Sidebar closeSidebar={closeSidebar} handleResize={handleResize}>
        <Component
          {...pageProps}
          setCloseSidebar={setCloseSidebar}
          handleSidebar={handleSidebar}
        />
      </Sidebar>
    </>
  );
}
